version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      python-packages:
        patterns:
              - "*"
    ignore:
      - dependency-name: "pyzx"
