version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      python-packages:
        patterns:
          - "*"
    ignore:
      - dependency-name: "qiskit"
        # There is a bug with Mypy and Qiskit 2.4.0
        # See https://github.com/python/mypy/issues/21263
        versions: [ ">=2.4" ]
