name: isort
on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - uses: isort/isort-action@master
        with:
          requirementsFiles: "requirements.txt requirements-dev.txt"
          isortVersion: "5.13.2"
