name: lint

on:
  pull_request:
    branches: [ "master" ]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install black
        run: pip install black

      - uses: actions/checkout@v2

      - name: Run black
        run: black -l 100 graphix/ tests/ --check
